# Generated by Django 6.0.2 on 2026-02-28 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, help_text='Who typed this entry (worker/foreman/admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries_entered', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='core.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries_reviewed', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='core.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['work_date'], name='core_timeen_work_da_a7c9c8_idx'), models.Index(fields=['status', 'work_date'], name='core_timeen_status_f53c9a_idx'), models.Index(fields=['project', 'work_date'], name='core_timeen_project_54547a_idx'), models.Index(fields=['worker', 'work_date'], name='core_timeen_worker__49a275_idx')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'project', 'work_date'), name='uniq_worker_project_day')],
            },
        ),
        migrations.CreateModel(
            name='RateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_overrides', to='core.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_overrides', to='core.worker')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('worker', 'project', 'effective_from'), name='uniq_worker_project_effective')],
            },
        ),
    ]
