# Generated by Django 6.0.2 on 2026-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accessrequest_magiclinktoken'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeentry',
            name='uniq_worker_project_day',
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERWRITTEN', 'Overwritten')], default='DRAFT', max_length=20),
        ),
    ]
