# Generated by Django 6.0.2 on 2026-03-01 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_timeentry_uniq_worker_project_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Parking cost in dollars', max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_entries', to='core.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_entries_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_entries_submitted', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_entries', to='core.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['work_date'], name='core_parkin_work_da_b80945_idx'), models.Index(fields=['status', 'work_date'], name='core_parkin_status_538173_idx'), models.Index(fields=['project', 'work_date'], name='core_parkin_project_e62d11_idx'), models.Index(fields=['worker', 'work_date'], name='core_parkin_worker__8adc69_idx')],
            },
        ),
    ]
