# Generated by Django 6.0.2 on 2026-03-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parkingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingentry',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Photo of parking receipt', null=True, upload_to='parking_receipts/%Y/%m/'),
        ),
    ]
