# Generated by Django 6.0.2 on 2026-03-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parkingentry_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingentry',
            name='receipt',
            field=models.FileField(blank=True, help_text='Photo or PDF of parking receipt (JPG, PNG, HEIC, WEBP, PDF — max 10MB)', null=True, upload_to='parking_receipts/%Y/%m/'),
        ),
    ]
