# Generated by Django 6.0.2 on 2026-03-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_parkingentry_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiclinktoken',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='rateoverride',
            name='uniq_worker_project_effective',
        ),
        migrations.DeleteModel(
            name='MagicLinkToken',
        ),
        migrations.DeleteModel(
            name='RateOverride',
        ),
    ]
