# Generated by Django 6.0.2 on 2026-03-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_magiclinktoken_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRequest',
        ),
    ]
