# Generated by Django 6.0.2 on 2026-06-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sync_username_to_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingentry',
            options={'verbose_name_plural': 'Parking entries'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name_plural': 'Time entries'},
        ),
    ]
